version: "3"

services:
  bot:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      ELUDRIS_HTTP_URL: ${ELUDRIS_HTTP_URL-}
      ELUDRIS_WS_URL: ${ELUDRIS_WS_URL-}
